### ISSUE TITLE
初始化MqttDefaultFilePersistence NullPointerException

### ISSUE THREAD

**Issue by flystarts** [huaweicloud/huaweicloud-iot-device-sdk-java#12]
Exception in thread "main" java.lang.NullPointerException
	at org.eclipse.paho.client.mqttv3.internal.MqttPersistentData.<init>(MqttPersistentData.java:63)
	at org.eclipse.paho.client.mqttv3.persist.MqttDefaultFilePersistence.get(MqttDefaultFilePersistence.java:219)
	at org.eclipse.paho.client.mqttv3.internal.ClientState.restoreState(ClientState.java:342)
	at org.eclipse.paho.client.mqttv3.internal.ClientState.<init>(ClientState.java:172)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.<init>(ClientComms.java:108)
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.<init>(MqttAsyncClient.java:470)
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.<init>(MqttAsyncClient.java:320)
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.<init>(MqttAsyncClient.java:315)
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.<init>(MqttAsyncClient.java:210)
	at com.huaweicloud.sdk.iot.device.transport.mqtt.MqttConnection.connect(MqttConnection.java:105)
	at com.huaweicloud.sdk.iot.device.client.DeviceClient.connect(DeviceClient.java:93)
	at com.huaweicloud.sdk.iot.device.service.AbstractDevice.init(AbstractDevice.java:120)
	at com.huaweicloud.sdk.iot.device.IoTDevice.init(IoTDevice.java:90)
	at com.huaweicloud.sdk.iot.device.demo.MessageSample.main(MessageSample.java:28)

**Comment by flystarts** [comment]
这个问题是paho的bug：https://github.com/eclipse/paho.mqtt.java/issues/634
如果使用默认的文件持久化MqttDefaultFilePersistence，它会把还未确认的消息保存在文件中。重启时从文件读取消息重发。但是读文件代码有bug会出现空指针。
目前paho还未修复此问题

**Comment by flystarts** [comment]
MqttDefaultFilePersistence替换为MemoryPersistence

**Comment by qingquaner** [comment]
这里做了个非null判断
![image](https://github.com/huaweicloud/huaweicloud-iot-device-sdk-java/assets/20200473/789b0b76-220c-48f3-ae71-6c3dc8673bbb)
最新版1.2.5 解决了这个问题吗？
